# Generated by Django 5.0 on 2023-12-20 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=550, verbose_name='description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='cover')),
                ('author', models.ForeignKey(on_delete=models.SET('The author has been removed'), related_name='author_books', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
