# Generated by Django 5.0 on 2023-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.FileField(default='default_content.txt', upload_to='content', verbose_name='content'),
        ),
    ]
