# Generated by Django 5.0 on 2023-12-20 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('The author has been removed'), related_name='author_books', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.FileField(default='default_content.txt', upload_to='content/', verbose_name='content'),
        ),
    ]
